<link rel="stylesheet" type="text/css" href="/css/auth.css"/>
<div id="wrap">

    <div id="center">
        <div id="logo">
            <img src="img/lgoo.jpg"/>
        </div>
        <div id="caixa">
            <div id="titulo">
                <img src="img/autenticacao.png"/>
            </div>
            <div id="corpo">

                <div id="irmnet">
                    <img src="img/irmnet-lego.png"/>
                </div>
                <?php
                if ($this->messages) {
                    ?>
                    <div class="alert alert-error">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Erro:</strong> 
                        <?php foreach ($this->messages as $message): ?>
                            <?php echo $message; ?>
                        <?php endforeach; ?>
                    </div>

                    <?php
                }
                ?>
                <div id="logon">
                    <form id="form" action="<?php echo $this->url('login', array());?>" method="post">
                        <input placeholder="Usuário da rede" name="login" type="text" id="login" />
                        <input placeholder="Senha da rede" type="password" name="senha" id="senha" />
                        <a href="#" id="enviar"></a>
                    </form>
                </div>

            </div>

        </div>

    </div>
</div>
<script>
    $(document).ready(function() {
        $(".alert").alert();
        $("#senha").keypress(function(e) {
            if (e.keyCode == 13)
            {
                $("#form").submit();
            }
        });
        $('#enviar').click(function() {
            $("#form").submit();
        });
    });
</script>
