<div class="page-header">
    <h1>IRM Net</h1>

    <h2>Autenticação</h2>
    <h4>Use seu usuário/senha da rede</h4>

</div>
<div class="page-footer">

    <?php
    if ($this->messages) {
        ?>
        <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>Erro</strong><?php echo $this->messages;?>
        </div>
       
        <?php
    }
    $form = $this->form;
    $form->setAttribute('action', $this->url('login', array()));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('login'));
    echo $this->formRow($form->get('senha'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>
</div>